(in-package "ACL2")

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; hb1384_core.lisp  —  v2.0 (hybrid encapsulate architecture)
;; Neutral legal vocabulary and generic legality/illegality conditions.
;; Generated by the Constitutional ACL2 Stress-Test Agent.
;;
;; This book defines uninterpreted predicates (defstub) and neutral
;; helper functions (defun).  It does not contain any facts,
;; interpretations, or assumptions.  All models include this book.
;;
;; Domain: Virginia constitutional amendment referral process
;; Subject: HB 1384 — redistricting amendment (2024-2026)
;; Constitutional provisions: Virginia Constitution Article XII, § 1
;;   (Amendment procedure); Article IV, § 12 (Single object rule);
;;   Article II, § 6 (Apportionment)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;; =========================================================================
;;; Ontological predicates — the base vocabulary
;;; =========================================================================

(defstub amendmentp (x) t)                       ; x is a proposed constitutional amendment
(defstub enrolled-actp (x) t)                    ; x is an enrolled act of the General Assembly
(defstub electionp (x) t)                        ; x is an election event
(defstub ballotreferencep (x) t)                 ; x is a ballot referendum question

;;; =========================================================================
;;; Temporal predicates
;;; =========================================================================

(defstub first-passage-datep (amend d) t)        ; amendment's first passage occurred on day d
(defstub second-passage-datep (amend d) t)       ; amendment's second passage occurred on day d
(defstub final-passage-datep (amend d) t)        ; final passage day d (may equal second)
(defstub election-occurrence-datep (elec d) t)   ; election legally "occurred" on day d
(defstub submission-datep (amend d) t)           ; amendment "submitted to voters" on day d
(defstub early-voting-start-datep (elec d) t)    ; early voting for election began on day d
(defstub election-day-datep (elec d) t)          ; official election day is day d

;;; =========================================================================
;;; Article XII sequencing predicates
;;; =========================================================================

(defstub first-passage-validp (amend) t)         ; first passage is constitutionally valid
(defstub intervening-election-qualifiesp (amend elec) t)
  ;; the election satisfies the "next general election" requirement

(defstub second-passage-after-electionp (amend elec) t)
  ;; second passage occurred after the intervening election

(defstub ninety-day-rule-satisfiedp (amend) t)
  ;; >= 90 days between final passage and submission to voters

;;; =========================================================================
;;; Void challenge predicates (P1 hinge)
;;; =========================================================================

(defstub first-passage-challenged-as-voidp (amend) t)
  ;; judicial challenge: first passage void ab initio

(defstub void-challenge-survivablep (amend) t)
  ;; whether the amendment survives the void challenge

;;; =========================================================================
;;; Election type predicates (P2 hinge)
;;; =========================================================================

(defstub general-electionp (elec) t)             ; election is a general election
(defstub election-after-first-passagep (amend elec) t)
  ;; election occurs after first passage date

;;; =========================================================================
;;; Notice / publication predicates (P5 hinge)
;;; =========================================================================

(defstub section-30-13-compliantp (amend) t)     ; strict § 30-13 publication occurred
(defstub notice-satisfiedp (amend) t)            ; notice requirement is satisfied
                                                  ;; (interpretive: mandatory vs directory)

;;; =========================================================================
;;; Ballot disclosure predicates (P6)
;;; =========================================================================

(defstub amendment-contains-temporal-windowp (amend) t)
  ;; amendment text has a temporal limitation (2025-2030)

(defstub amendment-contains-trigger-conditionp (amend) t)
  ;; amendment text has an external trigger condition (another state's action)

(defstub ballot-discloses-temporal-limitp (ballot) t)
  ;; ballot text discloses the temporal limitation to voters

(defstub ballot-discloses-trigger-conditionp (ballot) t)
  ;; ballot text discloses the trigger condition to voters

(defstub temporal-window-materialp (amend) t)
  ;; the temporal window is material for ballot disclosure

(defstub trigger-condition-materialp (amend) t)
  ;; the trigger condition is material for ballot disclosure

;;; =========================================================================
;;; Single object predicates (P7)
;;; =========================================================================

(defstub amendment-modifies-article-iip (amend) t)
  ;; the enrolled act modifies Article II of the Virginia Constitution

(defstub amendment-modifies-schedulep (amend) t)
  ;; the enrolled act modifies the Schedule of the Virginia Constitution

(defstub single-object-satisfiedp (amend) t)
  ;; the act satisfies Article IV, § 12 single-object rule

;;; =========================================================================
;;; Venue provision predicates (P8)
;;; =========================================================================

(defstub richmond-exclusive-venuep (amend) t)
  ;; the act mandates Richmond as exclusive venue

(defstub venue-transfers-pending-casesp (amend) t)
  ;; the act forces transfer of pending cases to Richmond

(defstub venue-centralization-permittedp (amend) t)
  ;; venue centralization is constitutionally permitted

(defstub transfer-pending-cases-permittedp (amend) t)
  ;; forced transfer of pending cases is constitutionally permitted

;;; =========================================================================
;;; Neutral helper functions — intermediate predicates
;;;
;;; These compose defstubs into the Article XII compliance conditions.
;;; Each maps to one of the eight predicates (P1–P8) identified in
;;; the Overview.  They are NEUTRAL structural compositions — the
;;; outcome depends entirely on how defstubs are constrained by the
;;; interpretive model files.
;;; =========================================================================

;; P1: First passage validity
;; If a void challenge exists, it must be survivable.
(defun first-passage-ok-p (amend)
  (implies (first-passage-challenged-as-voidp amend)
           (void-challenge-survivablep amend)))

;; P2: Next election sequencing
;; The intervening election must qualify (general + after first passage).
(defun next-election-ok-p (amend elec)
  (and (general-electionp elec)
       (election-after-first-passagep amend elec)
       (intervening-election-qualifiesp amend elec)))

;; P3: Second passage validity
;; Second passage must occur after the intervening election.
(defun second-passage-ok-p (amend elec)
  (second-passage-after-electionp amend elec))

;; P4: 90-day rule
;; At least 90 days between final passage and submission to voters.
(defun ninety-day-rule-ok-p (amend)
  (ninety-day-rule-satisfiedp amend))

;; P5: Notice / publication
;; Notice requirement satisfied under the applicable theory.
(defun notice-ok-p (amend)
  (notice-satisfiedp amend))

;; P6: Ballot submission clause
;; If the amendment contains material limitations, the ballot must
;; disclose them.
(defun submission-clause-ok-p (amend ballot)
  (and (implies (temporal-window-materialp amend)
               (ballot-discloses-temporal-limitp ballot))
       (implies (trigger-condition-materialp amend)
               (ballot-discloses-trigger-conditionp ballot))))

;; P7: Single object rule
;; The act must satisfy Article IV, § 12.
(defun single-object-ok-p (amend)
  (single-object-satisfiedp amend))

;; P8: Venue provision
;; If exclusive venue or pending-case transfer exists, it must be
;; permitted.
(defun venue-ok-p (amend)
  (and (implies (richmond-exclusive-venuep amend)
               (venue-centralization-permittedp amend))
       (implies (venue-transfers-pending-casesp amend)
               (transfer-pending-cases-permittedp amend))))

;;; =========================================================================
;;; Generic legality / illegality conditions
;;;
;;; Pattern (from Overview.md):
;;;   LEGAL = P1 ∧ P2 ∧ P3 ∧ P4 ∧ P5 ∧ P6 ∧ P7 ∧ P8
;;;   ILLEGAL = ¬LEGAL
;;;
;;; These are parameterized over the amendment, election, and ballot
;;; so that general theorems can quantify over arbitrary inputs.
;;; =========================================================================

(defun legal-referral-conditionp (amend elec ballot)
  (and (first-passage-ok-p amend)
       (next-election-ok-p amend elec)
       (second-passage-ok-p amend elec)
       (ninety-day-rule-ok-p amend)
       (notice-ok-p amend)
       (submission-clause-ok-p amend ballot)
       (single-object-ok-p amend)
       (venue-ok-p amend)))

(defun illegal-referral-conditionp (amend elec ballot)
  (not (legal-referral-conditionp amend elec ballot)))
